dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cd Homework1
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Liux.deb -uroboter95:$BINTRAY_API_KEY "https://api.bintray.com/content/roboter95/otus-projects/Homework/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Liux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
